pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/pp9970/GitHub-code'
            }
        }
        stage('Build') {
            steps {
                bat 'npm run smoke'
            }
        }
        
    }
}
